CREATE SEQUENCE SEQ_PESS
MINVALUE 1
MAXVALUE 999
START WITH 1
INCREMENT BY 1
NOCACHE;
CREATE TABLE PESS
(
  PESS_CD     NUMBER(6) DEFAULT SEQ_PESS.NEXTVAL NOT NULL,
  PESS_NOME   VARCHAR2(50) NOT NULL,
  PESS_LOG    VARCHAR2(50) NOT NULL,
  PESS_NUM    NUMBER(6) NOT NULL
  PESS_BRO    VARCHAR2(50) NOT NULL,
  PESS_CID    VARCHAR2(50) NOT NULL,
  PESS_ESTD   VARCHAR2(50) NOT NULL,
  PESS_CEP    NUMBER(9) NOT NULL,
  PESS_TEL1   VARCHAR2(50) NOT NULL,
  PESS_TEL2   VARCHAR2(50) NULL,
  PESS_TEL3   VARCHAR2(50) NULL,
  PESS_EMAIL  VARCHAR2(50) NULL
)
ALTER TABLE PESS ADD CONSTRAINT PK_PESS_PESS_CD PRIMARY KEY (PESS_CD);

CREATE SEQUENCE SEQ_BENS
MINVALUE 1
MAXVALUE 999
START WITH 1
INCREMENT BY 1
NOCACHE;
CREATE TABLE BENS
(
  BENS_CD           NUMBER(6) DEFAULT SEQ_BENS.NEXTVAL NOT NULL,
  BENS_DESC         VARCHAR2(50) NOT NULL,
  BENS_VAL_ESTM     NUMBER(12,2) NOT NULL,
  PESS_CD           NUMBER(6) NOT NULL
)
ALTER TABLE BENS ADD CONSTRAINT PK_BENS_BENS_CD PRIMARY KEY (BENS_CD);
ALTER TABLE BENS ADD CONSTRAINT FK_BENS_PESS_CD FOREIGN KEY (PESS_CD) REFERENCES PESS (PESS_CD);

CREATE TABLE OBRAART
(
  BENS_CD           NUMBER(6) NOT NULL,
  OBRAART_DESC      VARCHAR2(50) NOT NULL,
  OBRAART_ANO_ELAB  DATE NOT NULL
)
ALTER TABLE OBRAART ADD CONSTRAINT PK_OBRAART_BENS_CD PRIMARY KEY (BENS_CD);
ALTER TABLE OBRAART ADD CONSTRAINT FK_OBRAART_BENS_CD FOREIGN KEY (BENS_CD) REFERENCES BENS (BENS_CD);

CREATE TABLE IMOV
(
  BENS_CD     NUMBER(6) NOT NULL,
  IMOV_LOG    VARCHAR2(50) NOT NULL,
  IMOV_NUM    NUMBER(6) NOT NULL
  IMOV_BRO    VARCHAR2(50) NOT NULL,
  IMOV_CID    VARCHAR2(50) NOT NULL,
  IMOV_ESTD   VARCHAR2(50) NOT NULL,
  IMOV_CEP    NUMBER(9) NOT NULL,
  IMOV_TAM    NUMBER(9) NOT NULL
)
ALTER TABLE OBRAART ADD CONSTRAINT PK_IMOV_BENS_CD PRIMARY KEY (BENS_CD);
ALTER TABLE OBRAART ADD CONSTRAINT FK_IMOV_BENS_CD FOREIGN KEY (BENS_CD) REFERENCES BENS (BENS_CD);

CREATE SEQUENCE SEQ_INSTFINAN
MINVALUE 1
MAXVALUE 999
START WITH 1
INCREMENT BY 1
NOCACHE;
CREATE TABLE INSTFINAN
(
  INSTFINAN_CD        NUMBER(6) DEFAULT SEQ_INSTFINAN.NEXTVAL NOT NULL,
  INSTFINAN_NOME      VARCHAR2(50) NOT NULL,
  INSTFINAN_AGE       VARCHAR2(50) NOT NULL,
  INSTFINAN_LOCL      VARCHAR2(50) NOT NULL,
  INSTFINAN_NOME_GERT VARCHAR2(50) NOT NULL
)
ALTER TABLE INSTFINAN ADD CONSTRAINT PK_INSTFINAN_INSTFINAN_CD PRIMARY KEY (INSTFINAN_CD);

CREATE TABLE TEL_INSTFINAN
(
  INSTFINAN_CD        NUMBER(6) NOT NULL,
  TEL_INSTFINAN_NUM   VARCHAR2(50) NOT NULL
)
ALTER TABLE TEL_INSTFINAN ADD CONSTRAINT PK_TEL_INSTFINAN_INSTFINAN_CD PRIMARY KEY (INSTFINAN_CD,TEL_INSTFINAN);
ALTER TABLE TEL_INSTFINAN ADD CONSTRAINT FK_TEL_INSTFINAN_INSTFINAN_CD FOREIGN KEY (INSTFINAN_CD) REFERENCES INSTFINAN (INSTFINAN_CD);

CREATE TABLE MONET
  BENS_CD          NUMBER(6) NOT NULL,
  MONET_TP_MOEDA   VARCHAR2(50) NOT NULL,
  INSTFINAN_CD     NUMBER(6) NOT NULL
)
ALTER TABLE MONET ADD CONSTRAINT PK_MONET_BENS_CD PRIMARY KEY (BENS_CD);
ALTER TABLE MONET ADD CONSTRAINT FK_MONET_BENS_CD FOREIGN KEY (BENS_CD) REFERENCES BENS (BENS_CD);
ALTER TABLE MONET ADD CONSTRAINT FK_MONET_INSTFINAN_CD FOREIGN KEY (INSTFINAN_CD) REFERENCES INSTFINAN (INSTFINAN_CD);

CREATE SEQUENCE SEQ_CART
MINVALUE 1
MAXVALUE 999
START WITH 1
INCREMENT BY 1
NOCACHE;
CREATE TABLE CART
(
  CART_CD     NUMBER(6) DEFAULT SEQ_CART.NEXTVAL NOT NULL,
  CART_RZ_SOC      VARCHAR2(50) NOT NULL,
  CART_NOME_TBLAO  VARCHAR2(50) NOT NULL,
  CART_NOME_ECVAO  VARCHAR2(50) NOT NULL,
  CART_LOG         VARCHAR2(50) NOT NULL,
  CART_NUM         NUMBER(6) NOT NULL
  CART_BRO         VARCHAR2(50) NOT NULL,
  CART_CID         VARCHAR2(50) NOT NULL,
  CART_ESTD        VARCHAR2(50) NOT NULL,
  CART_CEP         NUMBER(9) NOT NULL
)
ALTER TABLE CART ADD CONSTRAINT PK_CART_CART_CD PRIMARY KEY (CART_CD);

CREATE TABLE TEL_CART
(
  CART_CD        NUMBER(6) NOT NULL,
  TEL_CART_NUM   VARCHAR2(50) NOT NULL
)
ALTER TABLE TEL_CART ADD CONSTRAINT PK_TEL_CART_CART_CD PRIMARY KEY (CART_CD,TEL_CART_NUM);
ALTER TABLE TEL_CART ADD CONSTRAINT FK_TEL_CART_CART_CD FOREIGN KEY (CART_CD) REFERENCES CART (CART_CD);

CREATE SEQUENCE SEQ_TSTM
MINVALUE 1
MAXVALUE 999
START WITH 1
INCREMENT BY 1
NOCACHE;
CREATE TABLE TSTM
(
  TSTM_CD           NUMBER(6) DEFAULT SEQ_TSTM.NEXTVAL NOT NULL,
  TSTM_DT_ELAB      DATE NOT NULL,
  TSTM_DT_REGS      DATE NOT NULL,
  TSTM_NUM_REGS     NUMBER(12) NOT NULL,
  PESS_CD           NUMBER(6) NOT NULL,
  CART_CD           NUMBER(6) NOT NULL
)
ALTER TABLE TSTM ADD CONSTRAINT PK_TSTM_TSTM_CD PRIMARY KEY (TSTM_CD);
ALTER TABLE TSTM ADD CONSTRAINT FK_TSTM_PESS_CD FOREIGN KEY (PESS_CD) REFERENCES PESS (PESS_CD);
ALTER TABLE TSTM ADD CONSTRAINT FK_TSTM_BENS_CD FOREIGN KEY (BENS_CD) REFERENCES BENS (BENS_CD);

CREATE SEQUENCE SEQ_HERD
MINVALUE 1
MAXVALUE 999
START WITH 1
INCREMENT BY 1
NOCACHE;
CREATE TABLE HERD
(
  HERD_CD           NUMBER(6) DEFAULT SEQ_HERD.NEXTVAL NOT NULL,
  HERD_NOME         VARCHAR2(50) NOT NULL,
  HERD_TP_PRTC      VARCHAR2(50) NOT NULL,
  HERD_DT_NASC      DATE NOT NULL,
  HERD_LOG          VARCHAR2(50) NOT NULL,
  HERD_NUM          NUMBER(6) NOT NULL
  HERD_BRO          VARCHAR2(50) NOT NULL,
  HERD_CID          VARCHAR2(50) NOT NULL,
  HERD_ESTD         VARCHAR2(50) NOT NULL,
  HERD_CEP          NUMBER(9) NOT NULL
  TSTM_CD           NUMBER(6) NOT NULL
)
ALTER TABLE HERD ADD CONSTRAINT PK_HERD_HERD_CD PRIMARY KEY (HERD_CD);
ALTER TABLE HERD ADD CONSTRAINT FK_HERD_TSTM_CD FOREIGN KEY (TSTM_CD) REFERENCES TSTM (TSTM_CD);

CREATE TABLE TEL_HERD
(
  HERD_CD        NUMBER(6) NOT NULL,
  TEL_HERD_NUM   VARCHAR2(50) NOT NULL
)
ALTER TABLE TEL_HERD ADD CONSTRAINT PK_TEL_HERD_HERD_CD PRIMARY KEY (HERD_CD,TEL_HERD_NUM);
ALTER TABLE TEL_HERD ADD CONSTRAINT FK_TEL_HERD_HERD_CD FOREIGN KEY (HERD_CD) REFERENCES HERD (HERD_CD);

CREATE TABLE HERC
(
  BENS_CD        NUMBER(6) NOT NULL,
  HERD_CD        NUMBER(6) NOT NULL,
  HERC_DT_RECEB  DATE NOT NULL
)
ALTER TABLE HERC ADD CONSTRAINT PK_HERC_HERC_CD PRIMARY KEY (BENS_CD,HERD_CD);
ALTER TABLE HERC ADD CONSTRAINT FK_HERC_HERD_CD FOREIGN KEY (HERD_CD) REFERENCES HERD (HERD_CD);
ALTER TABLE HERC ADD CONSTRAINT FK_HERC_BENS_CD FOREIGN KEY (BENS_CD) REFERENCES BENS (BENS_CD);
